#!/bin/bash

function usage {
  echo
  echo "Welcome to Aitulab !"
  echo
  echo "SERVER: $0 server (start | stop)"
  echo "NGROK: $0 ngrok (start | stop)"
  echo "HACKING: $0 hacking"
  echo "SERVER: $0 nessus (start | stop)"
}


set -e

if [[ -z "$1" || "$1" == "-h" ]]
then
  usage
  exit 1
elif [[ "$1" == "clear" && -z "$2" ]]
then
  echo "Clearing everything..."
  exit 0
elif [[ "$1" == "hacking" && -z "$2" ]]
then
  docker run --rm --user $(id -u):$(id -g) -v "${PWD}:/home/user/data" --net=host --privileged -it hacktulab zsh
  exit 0
elif [[ "$1" == "server" && "$2" == "start" ]]
then
  docker run --rm -d -p 80:80 -p 443:443 --name server -v "${PWD}:/srv/data" rflathers/nginxserve
  exit 0
elif [[ "$1" == "server" && "$2" == "stop" ]]
then
  docker stop server
  exit 0
elif [[ "$1" == "ngrok" && "$2" == "start" ]]
then
  docker run --rm -d -p 80:80 -p 443:443 --name server -v "${PWD}:/srv/data" rflathers/nginxserve
  docker run --rm -it --link server --name ngrok wernight/ngrok ngrok http server:80
  exit 0
elif [[ "$1" == "ngrok" && "$2" == "stop" ]]
then
  docker stop server
  exit 0
elif [[ "$1" == "cyberchef" && "$2" == "start" ]]
then
  docker run --rm --name cyberchef -d -p 8000:8000 mpepping/cyberchef
  exit 0
elif [[ "$1" == "cyberchef" && "$2" == "stop" ]]
then
  docker stop cyberchef
  exit 0
elif [[ "$1" == "nessus" && "$2" == "start" ]]
then
  docker run --rm -d --name nessus -p 8834:8834 infoslack/nessus
  exit 0
elif [[ "$1" == "nessus" && "$2" == "stop" ]]
then
  docker stop nessus
  exit 0
else
  usage
  exit 1
fi
